name = "dealsoldier"
compatibility_date = "2024-01-15"

[site]
source = "dist"
[build]
command = "npm run build"
[build.upload]
format = "service-worker"

[[routes]]
pattern = "/*"
handler = "index.html"